# Welcome to Jekyll!
#
include:
  - robots.txt

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
# Site settings
title: "Brian Villanueva"
tagline: "Information Security and Enterprise Risk"
description: "Strategic cybersecurity leadership focused on defensible security programs, security culture, and risk-informed decision making."
owner: Villan Security LLC
first_published: 2025 # if migrating another site, the year of your first publish
email: Brian@villansecurity.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://villansecurity.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/bvill1
  linkedin-square: https://linkedin.com/in/brian-villanueva
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
